### ISSUE TITLE
Release version of the miv-rv32im-freertos-port-test build fails 

### ISSUE THREAD

**Issue by AntonKrug** [RISCV-on-Microsemi-FPGA/FreeRTOS#13]
When building with SoftConsole, the Debug variant build just fine, but the Release variant fails:

Build of configuration Release for project miv-rv32im-freertos-port-test

> Building file: ../FreeRTOS/portable/MemMang/heap_2.c
> Invoking: GNU RISC-V Cross C Compiler
> riscv64-unknown-elf-gcc -march=rv32im -mabi=ilp32 -msmall-data-limit=8 -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -DNDEBUG -I"/projects/FreeRTOS_on_Mi-V_Processor/miv-rv32im-freertos-port-test" -I"/projects/FreeRTOS_on_Mi-V_Processor/miv-rv32im-freertos-port-test/drivers/CoreGPIO" -I"/projects/FreeRTOS_on_Mi-V_Processor/miv-rv32im-freertos-port-test/drivers/CoreUARTapb" -I"/projects/FreeRTOS_on_Mi-V_Processor/miv-rv32im-freertos-port-test/hal" -I"/projects/FreeRTOS_on_Mi-V_Processor/miv-rv32im-freertos-port-test/riscv_hal" -std=gnu11 -MMD -MP -MF"FreeRTOS/portable/MemMang/heap_2.d" -MT"FreeRTOS/portable/MemMang/heap_2.o" -c -o "FreeRTOS/portable/MemMang/heap_2.o" "../FreeRTOS/portable/MemMang/heap_2.c"
> ../FreeRTOS/portable/MemMang/heap_2.c:86:10: fatal error: FreeRTOS.h: No such file or directory
>  #include "FreeRTOS.h"
>           ^~~~~~~~~~~~
> FreeRTOS/portable/MemMang/subdir.mk:18: recipe for target 'FreeRTOS/portable/MemMang/heap_2.o' failed
> compilation terminated.
> make: *** [FreeRTOS/portable/MemMang/heap_2.o] Error 1

**Comment by AntonKrug** [comment]
The cause could be as simple as using case insensitive naming while building it on a case-sensitive filesystem (Linux) which will not find the file.

**Comment by AntonKrug** [comment]
In the end it was not case insensitive naming, it was actually not including the whole folder. Pull request here #14

**Comment by kevinscully100** [comment]
Release configuration build now succeeds
