### ISSUE TITLE
Bug in Sofware_IRQHandler

### ISSUE THREAD

**Issue by jstraus59** [RISCV-on-Microsemi-FPGA/FreeRTOS#8]
Using the [Imperas OVP virtual platform](https://riscv.org/software-status/#ovpsim) I have found a bug in Software_IRQHandler() at line 368 in [port.c](https://github.com/RISCV-on-Microsemi-FPGA/FreeRTOS/blob/master/FreeRTOS_on_Mi-V_Processor/miv-rv32im-freertos-port-test/FreeRTOS/portable/GCC/RISCV/port.c#L368). When returning from an interrupt the following code:

```
		...
		__asm volatile("addi	sp, sp, 4 * 32");

		PRCI->MSIP[0] = 0x00;
		__asm volatile("mret");
```
is intended to restore all registers then return from interrupt. However the compiler generates the following instructions:
```
366       		__asm volatile("addi	sp, sp, 4 * 32");
80001950:   addi    sp,sp,128
368       		PRCI->MSIP[0] = 0x00;
80001954:   lui     a5,0x44000
80001958:   sw      zero,0(a5) # 0x44000000
369       		__asm volatile("mret");
```
thus the a5 register gets trashed before returning from the interrupt.

**Comment by AntonKrug** [comment]
Thank you very much for the report. 

Does this commit address the issue?

https://github.com/RISCV-on-Microsemi-FPGA/FreeRTOS/commit/8762459dc04a4a0a85fbd69ceb1144f1cf2fe67e#diff-3d202149e6723e4d16c94252f536fda5

Regards,
Anton

**Comment by jstraus59** [comment]
That fixes the issue. Thanks.

Jim
