### ISSUE TITLE
spike does not produce result, rather continues to be in a loop

### ISSUE THREAD

**Issue by Chakri-myneni** [RISCV-on-Microsemi-FPGA/FreeRTOS#9]
Hello everyone,
I am trying to run **riscv-spike.elf** using spike, following the steps mentioned in https://github.com/RISCV-on-Microsemi-FPGA/FreeRTOS/tree/master/FreeRTOS_on_Spike .

so when I use **spike riscv-spike.elf**, spike continues to continues to be in a loop and keeps on executing the instructions but does not produce any output(even after 30 mins).

My question
1. What can be the reason for looping of spike?
2. How can I fix this issue?

Thank you
Chakri

**Comment by AntonKrug** [comment]
I tried to replicate your problem, but it works for me. Can you specify what versions of the tools are you using? I think if there is no output fairly quickly then something else is wrong and there is no point to wait for so long (within few seconds your console should be full).

> Linking....
> Completed riscv-spike.elf
> 
> akrug@xeon32:~/projects/freertos_spike/FreeRTOS/FreeRTOS_on_Spike/Demo/riscv-spike$ spike riscv-spike.elf 
> Task - 1
> Task - 2
> Task - 2
> Task - 1
>

**Comment by AntonKrug** [comment]
Can you try it with this binary? It's the one which works in my setup.
[riscv-spike.zip](https://github.com/RISCV-on-Microsemi-FPGA/FreeRTOS/files/2469727/riscv-spike.zip)

**Comment by AntonKrug** [comment]
Can you confirm if you are still having the issues or you resolved them? Did the elf file work?
